### ISSUE TITLE
Code Review from Team B!

### ISSUE THREAD

**Issue by stefioj** [philippaSteinberg/EEP153-Proj3#10]
Hey guys!! Great code- a few points of possible improvement but nothing major- your code looks really clear and the visualizations look great as well :))

- In the last plotting section, consider using a for loop to iterate through the labels and their corresponding values for Dar Es Salaam and Mainland Rural. This would make your code more concise and easier to update if you need to add or remove data points
- In the following lines, you have some repeated code for years 2008 and 2012. You can wrap this code into a function to avoid repetition and make your code cleaner

Again, just really nitpicky code-legibility things, but nothing that's strictly necerssary. 

<3 from Team B

**Comment by philippaSteinberg** [comment]
Thanks, implemented your second point. Not quite sure what you mean for your second point. Perhaps a spreadsheet would solve this issue.
